USE SUCOS_VENDAS;

DROP TABLE IF EXISTS ITENS_NOTAS_FISCAIS;
DROP TABLE IF EXISTS NOTAS_FISCAIS;
DROP TABLE IF EXISTS TABELA_DE_CLIENTES;
DROP TABLE IF EXISTS TABELA_DE_PRODUTOS;
DROP TABLE IF EXISTS TABELA_DE_VENDEDORES;

CREATE TABLE TABELA_DE_CLIENTES(
	CPF varchar(11) NOT NULL,
	NOME varchar(100) NULL,
	ENDERECO_1 varchar(150) NULL,
	ENDERECO_2 varchar(150) NULL,
	BAIRRO varchar(50) NULL,
	CIDADE varchar(50) NULL,
	ESTADO varchar(2) NULL,
	CEP varchar(8) NULL,
	DATA_DE_NASCIMENTO date NULL,
	IDADE smallint NULL,
	SEXO varchar(1) NULL,
	LIMITE_DE_CREDITO float NULL,
	VOLUME_DE_COMPRA float NULL,
	PRIMEIRA_COMPRA bit NULL,
	PRIMARY KEY (CPF));
	
CREATE TABLE TABELA_DE_PRODUTOS(
	CODIGO_DO_PRODUTO varchar(10) NOT NULL,
	NOME_DO_PRODUTO varchar(50) NULL,
	EMBALAGEM varchar(20) NULL,
	TAMANHO varchar(10) NULL,
	SABOR varchar(20) NULL,
	PRECO_DE_LISTA float NOT NULL,
    PRIMARY KEY(CODIGO_DO_PRODUTO));
	
CREATE TABLE TABELA_DE_VENDEDORES(
	MATRICULA varchar(5) NOT NULL,
	NOME varchar(100) NULL,
	PERCENTUAL_COMISSAO float NULL,
	DATA_ADMISSAO date NULL,
	DE_FERIAS bit NULL,
	BAIRRO varchar(50) NULL,
 PRIMARY KEY(MATRICULA));
 
 CREATE TABLE NOTAS_FISCAIS(
	CPF varchar(11) NOT NULL,
	MATRICULA varchar(5) NOT NULL,
	DATA_VENDA date NULL,
	NUMERO int NOT NULL,
	IMPOSTO float NOT NULL,
    PRIMARY KEY (NUMERO),
	FOREIGN KEY (MATRICULA) REFERENCES TABELA_DE_VENDEDORES(MATRICULA),
	FOREIGN KEY (CPF) REFERENCES TABELA_DE_CLIENTES(CPF));

CREATE TABLE ITENS_NOTAS_FISCAIS(
	NUMERO int NOT NULL,
	CODIGO_DO_PRODUTO varchar(10) NOT NULL,
	QUANTIDADE int NOT NULL,
	PRECO float NOT NULL,
	PRIMARY KEY (NUMERO, CODIGO_DO_PRODUTO),
	FOREIGN KEY (CODIGO_DO_PRODUTO) REFERENCES TABELA_DE_PRODUTOS (CODIGO_DO_PRODUTO),
	FOREIGN KEY (NUMERO) REFERENCES NOTAS_FISCAIS (NUMERO));

    CREATE TABLE PRODUTO
(CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL, 
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));

CREATE TABLE VENDEDORES 
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIA BIT(10) NULL,
PRIMARY KEY (MATRICULA));

ALTER TABLE VENDEDORES RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;

USE vendas_sucos;

CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY (NUMERO));

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

USE vendas_sucos;

ALTER TABLE tabela_de_vendas RENAME Notas;

USE vendas_sucos;

CREATE TABLE itens_notas;
(NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE INT, 
PRECO FLOAT,
PRIMARY KEY (NUMERO, CODIGO));

ALTER TABLE itens_notas ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO),
REFERENCES NOTAS (NUMERO);

ALTER TABLE itens_notas ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO)
REFERENCES PRODUTOS (CODIGO);

USE vendas_sucos;

INSERT INT PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMABALAGEM, PRECO_LISTA)
VALUES ('1040107', 'Light - 350 ml - Melância', 'melância', '350 ml', 'Lata', 4.56);

SELECT * FROM PRODUTOS;

INSERT INT PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMABALAGEM, PRECO_LISTA)
VALUES ('1040108', 'Light - 350 ml - Graviola', 'Graviola', '350 ml', 'Lata', 4.00);

INSERT INT PRODUTOS
VALUES ('1040109', 'Light - 350 ml - Açai', 'Açai', '350 ml', 'Lata', 5.60);
